version: '3.1'

services:

  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: node_pg
    volumes:
      - ~/docker_data/postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer
    depends_on:
      - postgres
    restart: always
    ports:
      - 9090:8080